---
navbar_logo: "/img/gdg-salvador.svg"
# url: "http://gdg-salvador.github.io" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site
baseurl: ""

about: "O Google Developer Groups (GDG) das cidades de Salvador, Recife, Fortaleza, Belo Horizonte e Curitiba realizam no dia 28 de março o GDG DevFest Extended 2015. O objetivo é ser um evento focado nas tecnologias do Google, tendo como público alvo gestores, empreendedores, desenvolvedores e estudantes, acontecendo nos estados com participações locais e remotas. Gostou? Então inscreva-se!"

# Remove this coment and add your city image for show in website
# city_image: /img/igrejinha-pampulha-buenolucas.png

# Informations about event
call_to_action:
  link: "https://www.sympla.com.br/gdg-devfest-extended-salvador__30630"
  title: "Inscreva-se"

# Conference informations
conf:
  contacts:
    email: gdg.salvador@gmail.com
  cover_image: "/img/gdg-salvador.svg"
  description: "Google Developers Group - BA - DevFest Extendend"
  end_at: "17:30"
  map_key: AIzaSyCdv2cEruteJozLlFVXVagofxNPJuqy7jc
  place:
    address: "SENAI CIMATEC"
    city: "Salvador"
    geo_point:
      lat: -12.93857
      lon: -38.386982
    state: BA
    venue: "Av. Orlando Gomes, 1845 - Piatã"
  start_at: "8:30"
  sub_title: "28 de Março, Salvador"
  title: "GDG DevFest Extended Salvador"
  tracking_id: UA-60535075-1
  website_url: ""

description: ""

highlighter: pygments
markdown: redcarpet
paginate: 10

partners:
  - logo: "/img/google-developers.png"
    name: "Google Developers"
    url: ""

  - logo: /img/gdg-salvador.svg
    name: "GDG Salvador"
    url: ""

  - logo: /img/wtm.png
    name: "Women Techmakers"
    url: "https://developers.google.com/women-techmakers"

  - logo: /img/partners/lucasbueno.png
    name: "Lucas Bueno"
    url: "https://plus.google.com/+LucasBueno"

permalink: "/:year/:month/:day/:title"

schedule:
  - link: ""
    name: "GDG Salvador"
    photo: /img/gdg-salvador.svg
    presentation:
      remote: "false"
      description: ""
      time:
        hour: "8:30"
        turn: "am"
      title: Credenciamento

  - link: ""
    name: "GDG Salvador"
    photo: /img/gdg-salvador.svg
    presentation:
      remote: "false"
      description: ""
      time:
        hour: "8:50"
        turn: "am"
      title: Abertura



  - link: "#"
    name: "Juan José Rodriguez"
    photo: "/img/speakers/juan-rodriguez.jpg"
    presentation:
      remote: "true"
      description: "Compartilhar a experiencia de um Glass Explorer desde o inicio ate a reengenharia do programa"
      time:
        hour: "9:00"
        turn: "am"
      title: "Google Glass e as melhores experiencias do Programa Glass Explorer"

  - link: "#"
    name: "Wilson Mendes"
    photo: "/img/speakers/wilson-mendes.jpeg"
    presentation:
      remote: "false"
      description: 'Angularjs é um framework javascript construido e mantido pelo grupo de engenheiros do Google, ele usa o HTML como uma "template engine" aliado a conceitos de Orientação a Objetos, testes, dentre outros, no intuito de fornecer uma solução completa para o cliente-side de sua aplicação. Além disso tem total compatibilidade com as bibliotecas javascript mais utilizadas, como jQuery. é um novo conceito para desenvolvimento de web apps client-site.<br/><br/>Entenda as novidades que estão por vir com o AngularJS 2.0, as novas definições, facilidades, novos desafios e entenda o motivo do AngularJS ser um framework excelente para todos os momentos.<br/><br/><i>Wilson é GDE (Google Developer Expert) de AngularJS, organizador do GDG Salvador, apaixonado por tecnologia e ativo em várias comunidades com foco em desenvolvimento web, incluindo AngularJS, JavaScript, HTML5, CSS3, Workflow, web performance e segurança. Participa de organizações de eventos, palestra em conferências pelo Brasil e contribui com vários projetos open source.</i>'
      time:
        hour: "10:00"
        turn: "am"
      title: "O futuro dos WebApps com AngularJS 2.0"

  - link: "#"
    name: "Gláuber Brennon"
    photo: "/img/speakers/glauber.jpg"
    presentation:
      remote: "false"
      description: "A Representational State Transfer (REST), em português Transferência de Estado Representacional, é uma abstração da arquitetura Web e tem emergido como uma excelente opção para arquitetar Interface de Programação de Aplicações/aplicativos (conhecidos como API's) Web e mobile, dentre outros. Nesta apresentação você conhecerá mais sobre como construir uma API REST utilizando o microframework python Flask, além de dicas e truques sobre esta arquitetura"
      time:
        hour: "11:00"
        turn: "am"
      title: "Escrevendo API's REST com o Flask"

  - link: "#"
    name: "Eduardo Emery"
    photo: "/img/speakers/emery.jpg"
    presentation:
      remote: "true"
      description: "Descubra ferramentas e funcionalidades da Google que você não conhecia e que podem te ajudar na sua vida como desenvolvedor e no seu dia-a-dia. Além de conhecer mais sobre o programa de Jovens Embaixadores Google.<br/><i><b>Eduardo Emery</b> é Estudante de Engenharia de Controle e Automação na Universidade de Pernambuco, Jovem Embaixador Google da sua Universidade, certificado em AdWords, guia local Google, desenvolvedor e apaixonado por robótica.</i>"
      time:
        hour: "14:00"
        turn: "pm"
      title: "O Google que você não conhece!"

  - link: "#"
    name: "Rafael Verger"
    photo: "/img/speakers/rafael-verger.jpg"
    presentation:
      remote: "false"
      description: "A história de como o JavaScript entrou para o back-end do JusBrasil, maior portal de informação pública brasileiro; nosso primeiro projeto com Node.js e o que vem por aí!"
      time:
        hour: "15:00"
        turn: "pm"
      title: "JusBrasil.js"

  - link: "#"
    name: ""
    photo: "/img/gdg.png"
    presentation:
      remote: "false"
      description: ""
      time:
        hour: "16:00"
        turn: "pm"
      title: "Coffee Break e Networking"

  - link: "https://developers.google.com/groups/pulse/Brazil"
    name: GDGs
    photo: /img/gdg.png
    presentation:
      remote: "false"
      description: ""
      time:
        hour: "16:20"
        turn: "pm"
      title: "Painel sobre Internet das Coisas - IoT"

  - link: "#"
    name: "Mobilidade além do smartphone"
    photo: "/img/speakers/paulo-ortins.jpg"
    presentation:
      remote: "false"
      description: ' Mobilidade é só smartphone? Claro que não! Nessa palestra vamos conhecer novos brinquedos que já estão mudando ou vão mudar a forma com que interagimos no mundo. Se prepare para conhecer mais sobre beacons bluetooth, relógios (smart watches), óculos e até mesmo carros inteligentes!'
      time:
        hour: "17:20"
        turn: "pm"
      title: "A confirmar"

sponsors:
  - logo: "/img/senai.png"
    name: "Senai Cimatec"
    url: "http://portais.fieb.org.br/senai/senai-na-sua-cidade/salvador/cimatec.html"