## Site settings
title: GDG Salvador
email: gdg.salvador@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Google Developer Group Salvador.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gdg-salvador.github.io" # the base hostname & protocol for your site
twitter_username: gdgssa
github_username:  GDG-Salvador

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/

exclude: ['package.json', '_src', 'node_modules', 'vendor/bundle/ruby']